/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.FuncionarioData;
import extras.TratarFormularios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Funcionario;

/**
 *
 * @author thale
 */
public class JIFFuncionario extends javax.swing.JInternalFrame {

    private Funcionario func;
    private FuncionarioData funcData;
    private int acao;
    private ArrayList<Funcionario> listaDeFuncionarios;

    public JIFFuncionario() {
        try {
            func = new Funcionario();
            funcData = new FuncionarioData();
            listaDeFuncionarios = new ArrayList<>();
            acao = 0;
            initComponents();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        tfNomeFunc = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        tfCPF = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblPesquisa = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        spTabelaPesquisa = new javax.swing.JScrollPane();
        tbPesquisa = new javax.swing.JTable();
        lblEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfSenha = new javax.swing.JPasswordField();
        lblSenha = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Funcionários");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setText("Nome");
        lblNome.setEnabled(false);
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        tfNomeFunc.setEnabled(false);
        tfNomeFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeFuncActionPerformed(evt);
            }
        });
        getContentPane().add(tfNomeFunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 216, -1));

        lblCPF.setText("CPF");
        lblCPF.setEnabled(false);
        getContentPane().add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        tfCPF.setEnabled(false);
        tfCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCPFActionPerformed(evt);
            }
        });
        getContentPane().add(tfCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, -1));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        lblPesquisa.setText("Pesquisa");
        getContentPane().add(lblPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
        });
        getContentPane().add(tfPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 180, -1));

        tbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPesquisaMouseClicked(evt);
            }
        });
        spTabelaPesquisa.setViewportView(tbPesquisa);

        getContentPane().add(spTabelaPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 308, 92));

        lblEmail.setText("  Email");
        lblEmail.setEnabled(false);
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        tfEmail.setEnabled(false);
        getContentPane().add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, -1));

        tfSenha.setEnabled(false);
        getContentPane().add(tfSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 170, -1));

        lblSenha.setText("Senha");
        lblSenha.setEnabled(false);
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeFuncActionPerformed

    private void tfCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCPFActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        try {
            habilitarCampos(true);
            tfCPF.setText("");
            tfEmail.setText("");
            tfNomeFunc.setText("");
            tfSenha.setText("");

            btnCancelar.setEnabled(true);
            btnSalvar.setEnabled(true);
            btnEditar.setEnabled(false);
            btnNovo.setEnabled(false);
            btnExcluir.setEnabled(false);
            tbPesquisa.setEnabled(false);
            tfPesquisa.setEnabled(false);
            lblPesquisa.setEnabled(false);

            acao = 1;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            habilitarCampos(true);
            tbPesquisa.setEnabled(false);
            btnCancelar.setEnabled(true);
            btnNovo.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnSalvar.setEnabled(true);

            acao = 2;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            habilitarCampos(false);
            btnNovo.setEnabled(true);
            btnCancelar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnSalvar.setEnabled(false);

            tfPesquisa.setEnabled(true);
            lblPesquisa.setEnabled(true);
            tbPesquisa.setEnabled(true);

            tfCPF.setText("");
            tfEmail.setText("");
            tfNomeFunc.setText("");
            tfSenha.setText("");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    if (acao == 1) {
                        if (funcData.cadastrarFuncionario(func)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu sistemas", JOptionPane.INFORMATION_MESSAGE);
                            btnCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Não salvou!!");
                        }
                    }
                    if (acao == 2) {
                        if (funcData.editar(func)) {
                            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!", "Meu sistemas", JOptionPane.INFORMATION_MESSAGE);
                            btnCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Não atualizou!!");
                        }
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased
        try {
            DefaultTableModel mp = (DefaultTableModel) tbPesquisa.getModel();
            mp.setNumRows(0);
            if (tfPesquisa.getText().length() > 1) {
                listaDeFuncionarios = funcData.pesquisar(tfPesquisa.getText());
                for (Funcionario p : listaDeFuncionarios) {
                    mp.addRow(new String[]{p.getCpf(), p.getNome_func()});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tfPesquisaKeyReleased

    private void tbPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPesquisaMouseClicked
        try {
            int linhaSelecionada = tbPesquisa.getSelectedRow();
            if (linhaSelecionada > -1) {
                tfCPF.setText(listaDeFuncionarios.get(linhaSelecionada).getCpf());
                tfNomeFunc.setText(listaDeFuncionarios.get(linhaSelecionada).getNome_func());
                tfEmail.setText(listaDeFuncionarios.get(linhaSelecionada).getEmail());
                tfSenha.setText(listaDeFuncionarios.get(linhaSelecionada).getSenha());

                btnEditar.setEnabled(true);
                btnExcluir.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tbPesquisaMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            if (funcData.excluir(tfCPF.getText())) {
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
                TratarFormularios.limparCampos(this);
                btnEditar.setEnabled(false);
                btnExcluir.setEnabled(false);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JScrollPane spTabelaPesquisa;
    private javax.swing.JTable tbPesquisa;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNomeFunc;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JPasswordField tfSenha;
    // End of variables declaration//GEN-END:variables

    public void habilitarCampos(boolean valor) {
        lblCPF.setEnabled(valor);
        lblEmail.setEnabled(valor);
        lblNome.setEnabled(valor);
        lblSenha.setEnabled(valor);

        tfCPF.setEnabled(valor);
        tfEmail.setEnabled(valor);
        tfNomeFunc.setEnabled(valor);
        tfSenha.setEnabled(valor);
    }

    private boolean validarCampos() {
        String msg = "";
        if (tfNomeFunc.getText().length() < 3) {
            msg += "\nO nome deve ter pelo menos 3 caracteres";
        }
        if (tfNomeFunc.getText().length() > 100) {
            msg += "\nO nome deve ter menos de 100 caracteres";
        }
        if (tfEmail.getText().length() < 3) {
            msg += "\nO email deve ter pelo menos de 3 caracteres";
        }
        if (!tfEmail.getText().contains("@")) {
            msg += "\nO email é inválido";
        }
        if (tfSenha.getText().length() < 5) {
            msg += "\nA senha deve ter pelo menos 5 caracteres";
        }
        if (tfSenha.getText().length() > 20) {
            msg += "\nA senha deve ter no máximo 20 caracteres";
        }

        if (msg.length() == 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Corrija os seguintes campos:" + msg,
                    "Meu sistema", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean preencherObjeto() {
        func.setCpf(tfCPF.getText());
        func.setNome_func(tfNomeFunc.getText());
        func.setEmail(tfEmail.getText());
        func.setSenha(tfSenha.getText());
        return true;
    }

}
