/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.ProdutoData;
import extras.TratarFormularios;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;

/**
 *
 * @author thale
 */
public class JIFProduto extends javax.swing.JInternalFrame {

    private Produto produto;
    private ProdutoData produtoData;
    private ArrayList<Produto> listaDeProdutos;
    private int acao = 0;

    public JIFProduto() {
        try {

            produto = new Produto();
            produtoData = new ProdutoData();
            listaDeProdutos = new ArrayList<>();
            initComponents();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblValorID = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfValor = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lblPesquisa = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Produtos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setText("ID");
        lblID.setEnabled(false);
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 28, -1, -1));

        lblValorID.setText("0");
        lblValorID.setEnabled(false);
        getContentPane().add(lblValorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 28, -1, -1));

        lblNome.setText("Nome");
        lblNome.setEnabled(false);
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 56, -1, -1));

        tfNome.setEnabled(false);
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 53, 130, -1));

        tfValor.setEnabled(false);
        getContentPane().add(tfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 84, 130, -1));

        lblValor.setText("Valor");
        lblValor.setEnabled(false);
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 87, -1, -1));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        lblPesquisa.setText("Pesquisa");
        getContentPane().add(lblPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
        });
        getContentPane().add(tfPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 170, -1));

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "VALOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdutosMouseClicked(evt);
            }
        });
        tableProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableProdutosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableProdutos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 390, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        try {
            TratarFormularios.habilitarCampos(this);
            tfPesquisa.setEnabled(false);
            tableProdutos.setEnabled(false);
            btnNovo.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            lblID.setEnabled(true);
            lblNome.setEnabled(true);
            lblPesquisa.setEnabled(true);
            lblValor.setEnabled(true);
            lblPesquisa.setEnabled(false);

            acao = 1;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            TratarFormularios.desabilitarCampos(this);
            tfPesquisa.setEnabled(true);
            tableProdutos.setEnabled(true);
            btnNovo.setEnabled(true);
            lblID.setEnabled(false);
            lblNome.setEnabled(false);
            lblPesquisa.setEnabled(false);
            lblValor.setEnabled(false);
            lblPesquisa.setEnabled(true);
            lblValorID.setEnabled(false);
            tfNome.setText("");
            tfValor.setText("");
            lblValorID.setText("0");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            if (validarCampos()) {
                if (preencherObjeto()) {
                    if (acao == 1) {
                        if (produtoData.cadastrarProduto(produto)) {
                            JOptionPane.showMessageDialog(this, "Salvo com sucesso!", "Meu sistemas", JOptionPane.INFORMATION_MESSAGE);
                            btnCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Não salvou!!");
                        }
                    }
                    if (acao == 2) {
                        if (produtoData.editar(produto)) {
                            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!", "Meu sistemas", JOptionPane.INFORMATION_MESSAGE);
                            btnCancelarActionPerformed(evt);
                        } else {
                            JOptionPane.showMessageDialog(this, "Não atualizou!!");
                        }
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tableProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableProdutosKeyReleased

    }//GEN-LAST:event_tableProdutosKeyReleased

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased
        try {
            DefaultTableModel mp = (DefaultTableModel) tableProdutos.getModel();
            mp.setNumRows(0);
            if (tfPesquisa.getText().length() > 1) {
                listaDeProdutos = produtoData.pesquisar(tfPesquisa.getText());
                for (Produto p : listaDeProdutos) {
                    mp.addRow(new String[]{"" + p.getIdProduto(), p.getNome_produto(), "" + p.getValor_produto()});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tfPesquisaKeyReleased

    private void tableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutosMouseClicked
        try {
            int linhaSelecionada = tableProdutos.getSelectedRow();
            if (linhaSelecionada > -1) {
                lblValorID.setText("" + listaDeProdutos.get(linhaSelecionada).getIdProduto());
                tfNome.setText(listaDeProdutos.get(linhaSelecionada).getNome_produto());
                tfValor.setText("" + listaDeProdutos.get(linhaSelecionada).getValor_produto());

                btnEditar.setEnabled(true);
                btnExcluir.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tableProdutosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnNovo.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnSalvar.setEnabled(true);
        tableProdutos.setEnabled(false);

        lblValorID.setEnabled(true);
        lblNome.setEnabled(true);
        lblID.setEnabled(true);
        lblValor.setEnabled(true);

        tfNome.setEnabled(true);
        tfPesquisa.setEnabled(false);
        tfValor.setEnabled(true);

        acao = 2;
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            if (produtoData.excluir(Integer.parseInt(lblValorID.getText()))) {
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
                TratarFormularios.limparCampos(this);
                btnEditar.setEnabled(false);
                btnExcluir.setEnabled(false);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:" + e.getMessage(), "Erro ao pesquisar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorID;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPesquisa;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables

    private boolean validarCampos() {
        String msg = "";
        if (tfNome.getText().length() < 3) {
            msg += "\nO nome deve ter pelo menos 3 caracteres";
        }
        if (tfNome.getText().length() > 100) {
            msg += "\nO nome deve ter menos de 100 caracteres";
        }

        if (Integer.parseInt(tfValor.getText()) <= 0) {
            msg += "\nO valor do produto não pode ser 0";
        }
        if (msg.length() == 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Corrija os seguintes campos:" + msg,
                    "Meu sistema", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    }

    private boolean preencherObjeto() {
        produto.setIdProduto(Integer.parseInt(lblValorID.getText()));
        produto.setNome_produto(tfNome.getText());
        produto.setValor_produto(Double.parseDouble(tfValor.getText()));
        return true;
    }

}
